/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2.home;

/**
 *
 * @author User
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        analysis = new javax.swing.JButton();
        modelling = new javax.swing.JButton();
        summary = new javax.swing.JButton();
        input = new javax.swing.JTabbedPane();
        weli = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        sumi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mode = new javax.swing.JCheckBox();
        median = new javax.swing.JCheckBox();
        variance = new javax.swing.JCheckBox();
        mean = new javax.swing.JCheckBox();
        mean_dev = new javax.swing.JCheckBox();
        std_dev = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        sum_inp = new javax.swing.JTextPane();
        sum_submit = new javax.swing.JButton();
        anali = new javax.swing.JPanel();
        anali1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        anal_inp1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        anal_inp2 = new javax.swing.JTextPane();
        covar = new javax.swing.JCheckBox();
        corr = new javax.swing.JCheckBox();
        point_bi = new javax.swing.JCheckBox();
        anal_submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        modi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        model_inp1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        model_inp2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        model_inp3 = new javax.swing.JTextPane();
        model_submit = new javax.swing.JButton();
        x = new javax.swing.JRadioButton();
        var2 = new javax.swing.JRadioButton();
        var3 = new javax.swing.JRadioButton();
        z = new javax.swing.JRadioButton();
        y = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        indep2 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        indep1 = new javax.swing.JTextPane();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        output = new javax.swing.JTabbedPane();
        welo = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        sumo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        std_sam_ans = new javax.swing.JLabel();
        var_sam_ans = new javax.swing.JLabel();
        mean_ans = new javax.swing.JLabel();
        median_ans = new javax.swing.JLabel();
        mode_ans = new javax.swing.JLabel();
        meandev_ans = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        var_pop_ans = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        std_pop_ans = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        analo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        covar_pop_ans = new javax.swing.JLabel();
        covar_sam_ans = new javax.swing.JLabel();
        point_bi_ans = new javax.swing.JLabel();
        corr_ans = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        reg_eq = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        future = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(204, 0, 51));
        headerPanel.setPreferredSize(new java.awt.Dimension(270, 700));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Analyzing and Summarizing System");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(687, 687, 687)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 50));

        menuPanel.setBackground(new java.awt.Color(70, 70, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        analysis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        analysis.setText("Analysis");
        analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysisActionPerformed(evt);
            }
        });

        modelling.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modelling.setText("Modelling");
        modelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modellingActionPerformed(evt);
            }
        });

        summary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        summary.setText("Summarization");
        summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(summary, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(analysis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(analysis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(modelling, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 970));

        weli.setBackground(new java.awt.Color(51, 51, 51));
        weli.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel40.setBackground(new java.awt.Color(204, 0, 51));
        jLabel40.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 0, 51));
        jLabel40.setText("observe its patterns");

        jLabel41.setBackground(new java.awt.Color(204, 0, 51));
        jLabel41.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 0, 51));
        jLabel41.setText("Play with data to ");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("SWE1007- PROGRAMMING IN JAVA\nSteve Mathew D A (20MIS0047)\nNithish Kumar S (20MIS0024)\nDurga Shree N (20MIS0054)\n\n");
        jScrollPane9.setViewportView(jTextArea1);

        javax.swing.GroupLayout weliLayout = new javax.swing.GroupLayout(weli);
        weli.setLayout(weliLayout);
        weliLayout.setHorizontalGroup(
            weliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weliLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(weliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addGroup(weliLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel41))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        weliLayout.setVerticalGroup(
            weliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weliLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        input.addTab("tab1", weli);

        jLabel3.setBackground(new java.awt.Color(240, 0, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Summarization");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Input comma separated values (Example: 4,5,6,...):");

        mode.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mode.setText("Mode");

        median.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        median.setText("Median");

        variance.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        variance.setText("Variance");
        variance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianceActionPerformed(evt);
            }
        });

        mean.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mean.setText("Mean");

        mean_dev.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        mean_dev.setText("Mean Deviation");

        std_dev.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        std_dev.setText("Standard Deviation");
        std_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_devActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(sum_inp);

        sum_submit.setBackground(new java.awt.Color(0, 51, 51));
        sum_submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sum_submit.setForeground(new java.awt.Color(255, 255, 255));
        sum_submit.setText("SUBMIT");
        sum_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sum_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sumiLayout = new javax.swing.GroupLayout(sumi);
        sumi.setLayout(sumiLayout);
        sumiLayout.setHorizontalGroup(
            sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumiLayout.createSequentialGroup()
                .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sumiLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mean, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(median, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(216, 216, 216)
                        .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(std_dev, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variance, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mean_dev, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sumiLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel3))
                    .addGroup(sumiLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sumiLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(sum_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        sumiLayout.setVerticalGroup(
            sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mean, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(variance, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(median, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(std_dev, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(sumiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mean_dev, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sum_submit)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        input.addTab("tab2", sumi);

        jLabel7.setBackground(new java.awt.Color(240, 0, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Analysis");

        jScrollPane4.setViewportView(anal_inp1);

        jScrollPane5.setViewportView(anal_inp2);

        covar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        covar.setText("Covariance");
        covar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covarActionPerformed(evt);
            }
        });

        corr.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        corr.setText("Correlation");

        point_bi.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        point_bi.setText("Point Bi-Serial Correlation");

        anal_submit.setBackground(new java.awt.Color(0, 51, 51));
        anal_submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        anal_submit.setForeground(new java.awt.Color(255, 255, 255));
        anal_submit.setText("SUBMIT");
        anal_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anal_submitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Enter comma separated values of second variable (Example: 4,5,6,...):");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Enter comma separated values of first variable (Example: 4,5,6,...):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("(Enter the sequene of categorical variables as 0s and 1s for Point Bi-Serial Correlation)");

        javax.swing.GroupLayout anali1Layout = new javax.swing.GroupLayout(anali1);
        anali1.setLayout(anali1Layout);
        anali1Layout.setHorizontalGroup(
            anali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anali1Layout.createSequentialGroup()
                .addGroup(anali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anali1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(anali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(anali1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(anal_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(anali1Layout.createSequentialGroup()
                .addGroup(anali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anali1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(covar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(corr))
                    .addGroup(anali1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel7))
                    .addGroup(anali1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(point_bi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        anali1Layout.setVerticalGroup(
            anali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anali1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(anali1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(covar)
                    .addComponent(corr))
                .addGap(43, 43, 43)
                .addComponent(point_bi)
                .addGap(41, 41, 41)
                .addComponent(anal_submit)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout analiLayout = new javax.swing.GroupLayout(anali);
        anali.setLayout(analiLayout);
        analiLayout.setHorizontalGroup(
            analiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(anali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        analiLayout.setVerticalGroup(
            analiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(anali1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        input.addTab("tab3", anali);

        jLabel6.setBackground(new java.awt.Color(240, 0, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Modelling");

        jScrollPane1.setViewportView(model_inp1);

        jScrollPane3.setViewportView(model_inp2);

        jScrollPane6.setViewportView(model_inp3);

        model_submit.setBackground(new java.awt.Color(0, 51, 51));
        model_submit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        model_submit.setForeground(new java.awt.Color(255, 255, 255));
        model_submit.setText("SUBMIT");
        model_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_submitActionPerformed(evt);
            }
        });

        buttonGroup1.add(x);
        x.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        x.setText("x");

        buttonGroup2.add(var2);
        var2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        var2.setText("2 variables");
        var2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(var3);
        var3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        var3.setText("3 variables");

        buttonGroup1.add(z);
        z.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        z.setText("z");
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        buttonGroup1.add(y);
        y.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        y.setText("y");
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel26.setText("For which of the given variables do you require a regression equation?");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("y");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setText("x");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setText("z");

        jScrollPane7.setViewportView(indep2);

        jScrollPane8.setViewportView(indep1);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Enter value of independent variables (for 3 variables)");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Enter value of independent variable (for 2 variables)");

        javax.swing.GroupLayout modiLayout = new javax.swing.GroupLayout(modi);
        modi.setLayout(modiLayout);
        modiLayout.setHorizontalGroup(
            modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modiLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(var3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(modiLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(modiLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(modiLayout.createSequentialGroup()
                .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modiLayout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modiLayout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modiLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6))))
                    .addGroup(modiLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel6))
                    .addGroup(modiLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(modiLayout.createSequentialGroup()
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))
                    .addGroup(modiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35))
                    .addGroup(modiLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(model_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        modiLayout.setVerticalGroup(
            modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modiLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modiLayout.createSequentialGroup()
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(var2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(var3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modiLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modiLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y)
                            .addComponent(z))
                        .addGap(18, 18, 18)
                        .addGroup(modiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(model_submit)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        input.addTab("tab4", modi);

        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 700, 970));

        welo.setBackground(new java.awt.Color(51, 51, 51));

        jLabel42.setBackground(new java.awt.Color(204, 0, 51));
        jLabel42.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 0, 51));
        jLabel42.setText("appear here!");

        jLabel43.setBackground(new java.awt.Color(204, 0, 51));
        jLabel43.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 0, 51));
        jLabel43.setText("Output will ");

        javax.swing.GroupLayout weloLayout = new javax.swing.GroupLayout(welo);
        welo.setLayout(weloLayout);
        weloLayout.setHorizontalGroup(
            weloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weloLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(weloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addContainerGap(593, Short.MAX_VALUE))
        );
        weloLayout.setVerticalGroup(
            weloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weloLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        output.addTab("tab1", welo);

        jLabel5.setBackground(new java.awt.Color(240, 0, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Summarization");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Median:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Mode:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Mean:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Variance:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Mean Deviation:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Standard Deviation:");

        std_sam_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        std_sam_ans.setText("jLabel21");

        var_sam_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        var_sam_ans.setText("jLabel21");

        mean_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mean_ans.setText("jLabel21");

        median_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        median_ans.setText("jLabel21");

        mode_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mode_ans.setText("jLabel21");

        meandev_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        meandev_ans.setText("jLabel21");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Variance:");

        var_pop_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        var_pop_ans.setText("jLabel21");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Standard Deviation:");

        std_pop_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        std_pop_ans.setText("jLabel21");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("(Population)");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("(Population)");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("(Sample)");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("(Sample)");

        javax.swing.GroupLayout sumoLayout = new javax.swing.GroupLayout(sumo);
        sumo.setLayout(sumoLayout);
        sumoLayout.setHorizontalGroup(
            sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumoLayout.createSequentialGroup()
                .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sumoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sumoLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel20)))
                .addGap(17, 17, 17)
                .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sumoLayout.createSequentialGroup()
                        .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(median_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mean_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mode_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sumoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(std_pop_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sumoLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(std_sam_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sumoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(meandev_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sumoLayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(var_pop_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sumoLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel19))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sumoLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sumoLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel21))
                                        .addGroup(sumoLayout.createSequentialGroup()
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(var_sam_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(jLabel5)
                    .addGroup(sumoLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel22)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        sumoLayout.setVerticalGroup(
            sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(190, 190, 190)
                .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(var_pop_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mean_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(39, 39, 39)
                .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(median_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(var_sam_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(50, 50, 50)
                .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(mode_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(meandev_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sumoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(sumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_sam_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(std_pop_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(sumoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)))
                .addContainerGap(355, Short.MAX_VALUE))
        );

        output.addTab("tab2", sumo);

        jLabel23.setBackground(new java.awt.Color(240, 0, 51));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setText("Analysis");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Correlation:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Covariance:");

        point.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        point.setText("Point Bi-Serial Correlation:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Covariance:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("(Population)");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("(Sample)");

        covar_pop_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        covar_pop_ans.setText("jLabel21");

        covar_sam_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        covar_sam_ans.setText("jLabel21");

        point_bi_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        point_bi_ans.setText("jLabel21");

        corr_ans.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        corr_ans.setText("jLabel21");

        javax.swing.GroupLayout analoLayout = new javax.swing.GroupLayout(analo);
        analo.setLayout(analoLayout);
        analoLayout.setHorizontalGroup(
            analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analoLayout.createSequentialGroup()
                .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(analoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(analoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel28))
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(covar_pop_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corr_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(analoLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analoLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(41, 41, 41))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analoLayout.createSequentialGroup()
                                        .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(covar_sam_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(point_bi_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(analoLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel23)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        analoLayout.setVerticalGroup(
            analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(analoLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(covar_pop_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(covar_sam_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(corr_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(point)
                            .addComponent(point_bi_ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(analoLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(analoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))))
                .addContainerGap(566, Short.MAX_VALUE))
        );

        output.addTab("tab3", analo);

        jLabel33.setBackground(new java.awt.Color(240, 0, 51));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setText("Modelling");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setText("Regression equation");

        reg_eq.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        reg_eq.setText("jLabel35");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setText("This is the value of the dependent variable based on the given");

        future.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        future.setText("    jLabel35");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setText("Future prediction");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setText("independent variable(s)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(reg_eq, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(future, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(421, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(264, 264, 264)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(576, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel33)
                .addGap(38, 38, 38)
                .addComponent(jLabel34)
                .addGap(52, 52, 52)
                .addComponent(reg_eq, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(future, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addContainerGap(507, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(261, 261, 261)
                    .addComponent(jLabel38)
                    .addContainerGap(656, Short.MAX_VALUE)))
        );

        output.addTab("tab4", jPanel1);

        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 1030, 970));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryActionPerformed
        // TODO add your handling code here:
        input.setSelectedIndex(1);
    }//GEN-LAST:event_summaryActionPerformed

    private void analysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysisActionPerformed
        // TODO add your handling code here:
        input.setSelectedIndex(2);
    }//GEN-LAST:event_analysisActionPerformed

    private void modellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modellingActionPerformed
        // TODO add your handling code here:
        input.setSelectedIndex(3);
    }//GEN-LAST:event_modellingActionPerformed

    private void varianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varianceActionPerformed

    private void std_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_devActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_devActionPerformed

    
    private void sum_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sum_submitActionPerformed
            // TODO add your handling code here:
        String summary_input=sum_inp.getText();
        int arr[]={0,0,0,0,0,0};
        if(mean.isSelected()){
            arr[0]=1;
        }
        if(median.isSelected()){
            arr[1]=1;
        }
        if(mode.isSelected()){
            arr[2]=1;
        }
        if(variance.isSelected()){
            arr[3]=1;
        }
        if(std_dev.isSelected()){
            arr[4]=1;
        }
        if(mean_dev.isSelected()){
            arr[5]=1;
        }
        sum s=new sum();
        String val1[]=s.data(summary_input,arr);
        mean_ans.setText(val1[0]);
        median_ans.setText(val1[1]);
        mode_ans.setText(val1[2]);
        var_pop_ans.setText(val1[3]);
        var_sam_ans.setText(val1[4]);
        std_pop_ans.setText(val1[5]);
        std_sam_ans.setText(val1[6]);
        meandev_ans.setText(val1[7]);
        //sumo.setVisible(true);
        output.setSelectedIndex(1);
    }//GEN-LAST:event_sum_submitActionPerformed

    private void anal_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anal_submitActionPerformed
        // TODO add your handling code here:
        String analysis_input1=anal_inp1.getText();
        String analysis_input2=anal_inp2.getText();
        int arr[]={0,0,0};
        if(covar.isSelected()){
            arr[0]=1;
        }
        if(corr.isSelected()){
            arr[1]=1;
        }
        if(point_bi.isSelected()){
            arr[2]=1;
        }
        anal a=new anal();
        String val2[]=a.data2(analysis_input1,analysis_input2,arr);
        covar_pop_ans.setText(val2[0]);
        covar_sam_ans.setText(val2[1]);
        corr_ans.setText(val2[2]);
        point_bi_ans.setText(val2[3]);
        //analo.setVisible(true);
        output.setSelectedIndex(2);
    }//GEN-LAST:event_anal_submitActionPerformed

    private void var2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var2ActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void covarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_covarActionPerformed

    private void model_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_submitActionPerformed
        int arr[]={0,0,0,0,0};
        if(var2.isSelected()){
            arr[0]=1;
        }
        else if(var3.isSelected()){
            arr[1]=1;
        }
        if(x.isSelected()){
            arr[2]=1;
        }
        else if(y.isSelected()){
            arr[3]=1;
        }
        else if (z.isSelected()){
            arr[4]=1;
        }
        model m=new model();
        String modelling_input1=model_inp1.getText();
        String modelling_input2=model_inp2.getText();
        String val1[];
        if(arr[1]==1){
            String modelling_input3=model_inp3.getText();
            String ind1=indep1.getText();
            String ind2=indep2.getText();
            String ind=ind1+","+ind2;
            val1=m.data_three(modelling_input1, modelling_input2, modelling_input3, arr,ind);
        }
        else{
            String ind1=indep1.getText();
            val1=m.data_two(modelling_input1, modelling_input2, arr,ind1);
        }
        reg_eq.setText(val1[0]);
        future.setText(val1[1]);
        output.setSelectedIndex(3);
    }//GEN-LAST:event_model_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane anal_inp1;
    private javax.swing.JTextPane anal_inp2;
    private javax.swing.JButton anal_submit;
    private javax.swing.JPanel anali;
    private javax.swing.JPanel anali1;
    private javax.swing.JPanel analo;
    private javax.swing.JButton analysis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox corr;
    private javax.swing.JLabel corr_ans;
    private javax.swing.JCheckBox covar;
    private javax.swing.JLabel covar_pop_ans;
    private javax.swing.JLabel covar_sam_ans;
    private javax.swing.JLabel future;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextPane indep1;
    private javax.swing.JTextPane indep2;
    private javax.swing.JTabbedPane input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox mean;
    private javax.swing.JLabel mean_ans;
    private javax.swing.JCheckBox mean_dev;
    private javax.swing.JLabel meandev_ans;
    private javax.swing.JCheckBox median;
    private javax.swing.JLabel median_ans;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JCheckBox mode;
    private javax.swing.JLabel mode_ans;
    private javax.swing.JTextPane model_inp1;
    private javax.swing.JTextPane model_inp2;
    private javax.swing.JTextPane model_inp3;
    private javax.swing.JButton model_submit;
    private javax.swing.JButton modelling;
    private javax.swing.JPanel modi;
    private javax.swing.JTabbedPane output;
    private javax.swing.JLabel point;
    private javax.swing.JCheckBox point_bi;
    private javax.swing.JLabel point_bi_ans;
    private javax.swing.JLabel reg_eq;
    private javax.swing.JCheckBox std_dev;
    private javax.swing.JLabel std_pop_ans;
    private javax.swing.JLabel std_sam_ans;
    private javax.swing.JTextPane sum_inp;
    private javax.swing.JButton sum_submit;
    private javax.swing.JPanel sumi;
    private javax.swing.JButton summary;
    private javax.swing.JPanel sumo;
    private javax.swing.JRadioButton var2;
    private javax.swing.JRadioButton var3;
    private javax.swing.JLabel var_pop_ans;
    private javax.swing.JLabel var_sam_ans;
    private javax.swing.JCheckBox variance;
    private javax.swing.JPanel weli;
    private javax.swing.JPanel welo;
    private javax.swing.JRadioButton x;
    private javax.swing.JRadioButton y;
    private javax.swing.JRadioButton z;
    // End of variables declaration//GEN-END:variables
}
